name: rag_env
channels:
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - altair=5.0.1=py311haa95532_0
  - annotated-types=0.6.0=py311haa95532_0
  - anyio=4.2.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h2bbff1b_0
  - arrow-cpp=14.0.2=ha81ea56_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - babel=2.11.0=py311haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py311haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.7=py311hd7041d2_0
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=h2bbff1b_5
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2024.3.11=haa95532_0
  - certifi=2024.2.2=py311haa95532_0
  - cffi=1.16.0=py311h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - cryptography=42.0.5=py311h89fc84f_0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.8.0=py311haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py311haa95532_0
  - glog=0.5.0=hd77b12b_1
  - grpc-cpp=1.48.2=hfe90ff0_1
  - h11=0.14.0=py311haa95532_0
  - httpcore=1.0.2=py311haa95532_0
  - httpx=0.26.0=py311haa95532_0
  - idna=3.4=py311haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.28.0=py311haa95532_0
  - ipython=8.20.0=py311haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.8.1=py311haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py311haa95532_1
  - jinja2=3.1.3=py311haa95532_0
  - jira=3.6.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter-lsp=2.2.0=py311haa95532_0
  - jupyter_client=8.6.0=py311haa95532_0
  - jupyter_core=5.5.0=py311haa95532_0
  - jupyter_events=0.8.0=py311haa95532_0
  - jupyter_server=2.10.0=py311haa95532_0
  - jupyter_server_terminals=0.4.4=py311haa95532_1
  - jupyterlab=4.0.11=py311haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=24.3.1=py311haa95532_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcurl=8.5.0=h86230a5_0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=he2ea4bf_2
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown-it-py=2.2.0=py311haa95532_1
  - markupsafe=2.1.3=py311h2bbff1b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mdurl=0.1.0=py311haa95532_0
  - mistune=2.0.4=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - more-itertools=10.1.0=py311haa95532_0
  - nbclient=0.8.0=py311haa95532_0
  - nbconvert=7.10.0=py311haa95532_0
  - nbformat=5.9.2=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - notebook=7.0.8=py311haa95532_0
  - notebook-shim=0.2.3=py311haa95532_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - oauthlib=3.2.2=py311haa95532_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_0
  - orc=1.7.4=h623e30f_1
  - overrides=7.4.0=py311haa95532_0
  - packaging=23.2=py311haa95532_0
  - pandas=2.2.1=py311hea22821_0
  - pandas-stubs=2.1.4.231227=py311haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pillow=10.2.0=py311h2bbff1b_0
  - pip=23.3.1=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - prometheus_client=0.14.1=py311haa95532_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=14.0.2=py311h847bd2a_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeck=0.8.0=py311haa95532_2
  - pygments=2.15.1=py311haa95532_1
  - pyjwt=2.4.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=0.21.0=py311haa95532_0
  - python-fastjsonschema=2.16.2=py311haa95532_0
  - python-json-logger=2.0.7=py311haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pywin32-ctypes=0.2.2=py311haa95532_0
  - pywinpty=2.0.10=py311h5da7b33_0
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.2=py311hd77b12b_0
  - re2=2022.04.01=hd77b12b_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.31.0=py311haa95532_1
  - requests-oauthlib=1.3.0=py_0
  - requests-toolbelt=1.0.0=py311haa95532_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rich=13.3.5=py311haa95532_0
  - rpds-py=0.10.6=py311h062c2fa_0
  - send2trash=1.8.2=py311haa95532_0
  - setuptools=68.2.2=py311haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h6c2663c_1
  - sniffio=1.3.0=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - streamlit=1.32.0=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py311haa95532_0
  - tinycss2=1.2.1=py311haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py311haa95532_0
  - tornado=6.3.3=py311h2bbff1b_0
  - tqdm=4.65.0=py311h746a85d_0
  - traitlets=5.7.1=py311haa95532_0
  - types-pytz=2022.4.0.0=py311haa95532_1
  - typing-extensions=4.9.0=py311haa95532_1
  - typing_extensions=4.9.0=py311haa95532_1
  - tzdata=2024a=h04d1e81_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=0.58.0=py311haa95532_4
  - wheel=0.41.2=py311haa95532_0
  - widgetsnbextension=3.6.6=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.17.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - arrow==1.3.0
      - asgiref==3.8.1
      - atlassian-python-api==3.41.11
      - attrs==23.2.0
      - backoff==2.2.1
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - build==1.2.1
      - cached-property==1.5.2
      - cachetools==5.3.3
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.24
      - coloredlogs==15.0.1
      - commonmark==0.9.1
      - dataclasses-json==0.6.4
      - deprecated==1.2.14
      - dictdiffer==0.9.0
      - faiss-cpu==1.8.0
      - fastapi==0.110.2
      - filelock==3.13.4
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - google-ai-generativelanguage==0.4.0
      - google-api-core==2.18.0
      - google-auth==2.29.0
      - google-generativeai==0.4.1
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - groq==0.5.0
      - grpcio==1.62.1
      - grpcio-status==1.62.1
      - httptools==0.6.1
      - huggingface-hub==0.22.2
      - humanfriendly==10.0
      - humanize==4.9.0
      - importlib-metadata==7.0.0
      - importlib-resources==6.4.0
      - ipyvue==1.11.0
      - ipyvuetify==1.9.4
      - isoduration==20.11.0
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kubernetes==29.0.0
      - langchain==0.1.14
      - langchain-chroma==0.1.0
      - langchain-community==0.0.34
      - langchain-core==0.1.45
      - langchain-google-genai==1.0.1
      - langchain-groq==0.1.3
      - langchain-openai==0.1.3
      - langchain-text-splitters==0.0.1
      - langgraph==0.2.67
      - langsmith==0.1.38
      - markdown==3.6
      - marshmallow==3.21.1
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - notion==0.0.28
      - notion-client==2.2.1
      - notion-database==1.2.0
      - onnxruntime==1.17.3
      - openai==1.16.0
      - opentelemetry-api==1.24.0
      - opentelemetry-exporter-otlp-proto-common==1.24.0
      - opentelemetry-exporter-otlp-proto-grpc==1.24.0
      - opentelemetry-instrumentation==0.45b0
      - opentelemetry-instrumentation-asgi==0.45b0
      - opentelemetry-instrumentation-fastapi==0.45b0
      - opentelemetry-proto==1.24.0
      - opentelemetry-sdk==1.24.0
      - opentelemetry-semantic-conventions==0.45b0
      - opentelemetry-util-http==0.45b0
      - orjson==3.10.0
      - outcome==1.3.0.post0
      - posthog==3.5.0
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - pulsar-client==3.5.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygithub==2.3.0
      - pymdown-extensions==10.8
      - pymupdf==1.24.2
      - pymupdfb==1.24.1
      - pynacl==1.5.0
      - pypika==0.48.9
      - pyproject-hooks==1.0.0
      - pyreadline3==3.4.1
      - python-slugify==8.0.4
      - reacton==1.8.3
      - regex==2023.12.25
      - rich-click==1.7.4
      - rsa==4.9
      - selenium==4.20.0
      - shellingham==1.5.4
      - solara==1.32.0
      - solara-server==1.32.0
      - solara-ui==1.32.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.29
      - starlette==0.37.2
      - streamsync==0.5.0
      - sympy==1.12
      - tenacity==8.2.3
      - text-unidecode==1.3
      - tiktoken==0.6.0
      - tokenizers==0.19.1
      - trio==0.25.0
      - trio-websocket==0.11.1
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-inspect==0.9.0
      - tzlocal==5.2
      - uri-template==1.3.0
      - urllib3==1.26.18
      - uvicorn==0.29.0
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - webcolors==1.13
      - websockets==12.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.9.4
prefix: C:\Users\DELL\anaconda3\envs\rag_env
